name: secure_snap
description: "Secure Snap Project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: ^1.16.0
  provider: ^6.1.4
  go_router: ^15.0.0
  get_it: ^8.0.3
  intl: 0.19.0
  equatable: ^2.0.7
  sqlite3_flutter_libs: ^0.5.31
  drift: ^2.25.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.7.5
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  local_auth_platform_interface: ^1.0.10
  local_auth_darwin: ^1.4.3
  local_auth_windows: ^1.0.11
  test_api: ^0.7.4
  leak_tracker_flutter_testing: ^3.0.9

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.25.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - test/assets/